"""Upload finalized fp32 bundles to the private artifact store and write artifacts.ts.

    HF_TOKEN=... uv run python upload_bundle.py --bundles <dir> --checkpoints multilingual english typed-decisions

<dir>/<checkpoint>/fp32/ must hold the files finalize_bundle.py produced. Every bundle
goes to `<repo>/<checkpoint>/fp32/` in ONE commit, so a single HF revision pins all
of them. The script then re-reads the remote LFS SHA-256 of every file at that
revision, requires it to equal manifest.json, and rewrites
packages/laya/src/artifacts.ts.

The token comes from the environment only (HF_TOKEN, or HF_ACCESS_TOKEN inside the
swarm), never from a flag, so it cannot reach a command line or a log.
With --dry-run nothing is uploaded; the manifests are checked and artifacts.ts is
not touched. With --pin-only nothing is uploaded either: artifacts.ts is rewritten
from the manifests at the repo's current head (the export workflow uploads one
checkpoint per job, then pins once).
"""
import argparse
import json
import os

from huggingface_hub import CommitOperationAdd, HfApi

BUNDLE_FILES = ("encoder.onnx", "head.onnx", "tokenizer.json", "rl_agent_config.json")
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ARTIFACTS_TS = os.path.join(ROOT, "packages", "laya", "src", "artifacts.ts")


def token():
    t = os.environ.get("HF_TOKEN") or os.environ.get("HF_ACCESS_TOKEN")
    if not t:
        raise SystemExit("set HF_TOKEN (read and write access to the artifact repo)")
    return t


def load_manifest(bundles, checkpoint):
    d = os.path.join(bundles, checkpoint, "fp32")
    with open(os.path.join(d, "manifest.json"), encoding="utf-8") as f:
        m = json.load(f)
    if m["checkpoint"] != checkpoint or m["precision"] != "fp32":
        raise SystemExit("%s: manifest is for %s/%s" % (d, m["checkpoint"], m["precision"]))
    for name in BUNDLE_FILES:
        if os.path.getsize(os.path.join(d, name)) != m["files"][name]["bytes"]:
            raise SystemExit("%s/%s: size differs from manifest.json; rerun finalize_bundle.py" % (d, name))
    return d, m


def remote_sha256(api, repo, revision, paths):
    out = {}
    for info in api.get_paths_info(repo, paths, revision=revision, expand=True):
        out[info.path] = info.lfs.sha256 if info.lfs else None
    return out


def render_ts(repo, revision, manifests):
    lines = [
        "// Generated by tools/export/upload_bundle.py. Do not edit by hand.",
        "// Exported fp32 bundles in the private artifact store, pinned by revision and SHA-256.",
        "",
        "export type CheckpointName = \"english\" | \"multilingual\" | \"typed-decisions\";",
        "export type Precision = \"fp32\";",
        "",
        "export interface BundleArtifact {",
        "  /** Path inside the artifact repo, `<checkpoint>/<precision>`. */",
        "  subfolder: string;",
        "  /** Source checkpoint the bundle was exported from. */",
        "  source: { repo: string; revision: string };",
        "  bytes: Record<string, number>;",
        "  sha256: Record<string, string>;",
        "}",
        "",
        "export const ARTIFACT_REPO = %s;" % json.dumps(repo),
        "export const ARTIFACT_REVISION = %s;" % json.dumps(revision),
        "",
        "export const ARTIFACTS: Record<CheckpointName, Record<Precision, BundleArtifact>> = {",
    ]
    for ckpt in ("english", "multilingual", "typed-decisions"):
        m = manifests[ckpt]
        lines += [
            "  %s: {" % json.dumps(ckpt),
            "    fp32: {",
            "      subfolder: %s," % json.dumps("%s/fp32" % ckpt),
            "      source: { repo: %s, revision: %s }," % (json.dumps(m["hfRepo"]), json.dumps(m["hfRevision"])),
            "      bytes: {",
        ]
        lines += ["        %s: %d," % (json.dumps(n), m["files"][n]["bytes"]) for n in BUNDLE_FILES]
        lines += ["      },", "      sha256: {"]
        lines += ["        %s: %s," % (json.dumps(n), json.dumps(m["files"][n]["sha256"])) for n in BUNDLE_FILES]
        lines += ["      },", "    },", "  },"]
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--bundles", help="Local bundles root; required unless --pin-only.")
    p.add_argument("--repo", default="desplega/laya-onnx")
    p.add_argument("--checkpoints", nargs="+", default=["english", "multilingual", "typed-decisions"])
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--pin-only", action="store_true")
    args = p.parse_args(argv)

    found = {}
    if not args.pin_only:
        if not args.bundles:
            raise SystemExit("--bundles is required unless --pin-only")
        found = {c: load_manifest(args.bundles, c) for c in args.checkpoints}
    if args.dry_run:
        print("dry run: %d bundle(s) consistent with their manifests" % len(found))
        return
    api = HfApi(token=token())
    if args.pin_only:
        revision = api.model_info(args.repo).sha
    else:
        ops = []
        for ckpt, (d, _) in found.items():
            for name in BUNDLE_FILES + ("manifest.json",):
                ops.append(CommitOperationAdd("%s/fp32/%s" % (ckpt, name), os.path.join(d, name)))
        commit = api.create_commit(
            args.repo, operations=ops, repo_type="model",
            commit_message="fp32 bundles: %s" % ", ".join(args.checkpoints),
        )
        revision = commit.oid
        print("uploaded %s@%s" % (args.repo, revision))

    manifests = {}
    for ckpt in ("english", "multilingual", "typed-decisions"):
        if ckpt in found:
            m = found[ckpt][1]
        else:  # checkpoints this run did not upload keep their manifest at `revision`
            path = api.hf_hub_download(args.repo, "%s/fp32/manifest.json" % ckpt, revision=revision)
            with open(path, encoding="utf-8") as f:
                m = json.load(f)
        paths = ["%s/fp32/%s" % (ckpt, n) for n in BUNDLE_FILES]
        remote = remote_sha256(api, args.repo, revision, paths)
        for name in BUNDLE_FILES:
            want = m["files"][name]["sha256"]
            got = remote.get("%s/fp32/%s" % (ckpt, name))
            if got is not None and got != want:
                raise SystemExit("%s/fp32/%s: remote sha256 %s != manifest %s" % (ckpt, name, got, want))
        manifests[ckpt] = m
    with open(ARTIFACTS_TS, "w", encoding="utf-8") as f:
        f.write(render_ts(args.repo, revision, manifests))
    print("wrote %s" % os.path.relpath(ARTIFACTS_TS, ROOT))


if __name__ == "__main__":
    main()
