// Generated by tools/export/upload_bundle.py. Do not edit by hand.
// Exported fp32 bundles in the public artifact store, pinned by revision and SHA-256.

export type CheckpointName = "english" | "multilingual" | "typed-decisions";
export type Precision = "fp32";

export interface BundleArtifact {
  /** Path inside the artifact repo, `<checkpoint>/<precision>`. */
  subfolder: string;
  /** Source checkpoint the bundle was exported from. */
  source: { repo: string; revision: string };
  bytes: Record<string, number>;
  sha256: Record<string, string>;
}

export const ARTIFACT_REPO = "desplega/laya-onnx";
export const ARTIFACT_REVISION = "e1d00cd746843d098f4c1aa3179964243cecfec2";

export const ARTIFACTS: Record<CheckpointName, Record<Precision, BundleArtifact>> = {
  "english": {
    fp32: {
      subfolder: "english/fp32",
      source: { repo: "convaiinnovations/laya", revision: "55cf4c4ebb4ebe31b2550e8bdf3bd21b99753851" },
      bytes: {
        "encoder.onnx": 1582334685,
        "head.onnx": 106272385,
        "tokenizer.json": 3583228,
        "rl_agent_config.json": 745,
      },
      sha256: {
        "encoder.onnx": "a617f183bea68956cdacf80e970eee72865fea32a181a111be292614155e4b9b",
        "head.onnx": "275b74e1494dcb84a8aa4f486ba4b0d414a4143e85b9d9bb5f07af62ca70c6ee",
        "tokenizer.json": "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30",
        "rl_agent_config.json": "ae287b56bbcf5f8c4f4541ae9dfd00c914c4c48b940b8398c3058af37ba92bbd",
      },
    },
  },
  "multilingual": {
    fp32: {
      subfolder: "multilingual/fp32",
      source: { repo: "convaiinnovations/laya-multilingual", revision: "e4e9ddf21a7b1903b7acffd8814ad4307bf63a67" },
      bytes: {
        "encoder.onnx": 1230282662,
        "head.onnx": 60101236,
        "tokenizer.json": 34363188,
        "rl_agent_config.json": 472,
      },
      sha256: {
        "encoder.onnx": "4bf4feb8de3ee17e8032cf0c2fc506131d2e3c458dbe3ea82898d4d2d06fb1a6",
        "head.onnx": "03f78ddf0bfaa86f7b24e4298070bf9ac0a03516e64e8441552ecc2db89e1b3c",
        "tokenizer.json": "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f",
        "rl_agent_config.json": "25061739243b617ad88d1219ba6f8a9c86c5881ca28df024fa2d9b3b2fcc30c6",
      },
    },
  },
  "typed-decisions": {
    fp32: {
      subfolder: "typed-decisions/fp32",
      source: { repo: "convaiinnovations/laya-typed-decisions", revision: "1a793eb568e6718f15941d08f85432581df534e3" },
      bytes: {
        "encoder.onnx": 1582334685,
        "head.onnx": 106272385,
        "tokenizer.json": 3583228,
        "rl_agent_config.json": 847,
      },
      sha256: {
        "encoder.onnx": "14e9707c42a300667c5f195befc566d34c8a0fb5b2ea00b53d1c405559f8060e",
        "head.onnx": "212b39e45b99e4a5d866369b0757ea586e7a494ed004563624205a381e17d52a",
        "tokenizer.json": "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30",
        "rl_agent_config.json": "ebf0cd524d92342a6be5e48e9fca3d7c2babfb5a56ccd79d2171ef5d8c7f7be8",
      },
    },
  },
};
