apiVersion: apps/v1
kind: Deployment
metadata:
  name: laya-server
spec:
  template:
    spec:
      volumes:
        - name: cache
          emptyDir: null
          persistentVolumeClaim:
            claimName: laya-cache
